/*
 Generated by typeshare 1.13.4
*/

/** Opaque artifact identifier. Its value is validated for safe wire transport. */
export type ArtifactId = string;

/** Stable component identity: `cmp_` followed by lowercase unpadded Base32 BLAKE3-256. */
export type ComponentId = string;

export enum ComponentKind {
	Application = "APPLICATION",
	Package = "PACKAGE",
	Runtime = "RUNTIME",
	Tool = "TOOL",
	Harness = "HARNESS",
	McpServer = "MCP_SERVER",
	Skill = "SKILL",
	Agent = "AGENT",
	Hook = "HOOK",
	Plugin = "PLUGIN",
	Browser = "BROWSER",
	BrowserProfile = "BROWSER_PROFILE",
	Editor = "EDITOR",
	Extension = "EXTENSION",
	Configuration = "CONFIGURATION",
	DataArtifact = "DATA_ARTIFACT",
	SecretReference = "SECRET_REFERENCE",
	EnvironmentVariable = "ENVIRONMENT_VARIABLE",
	SystemFeature = "SYSTEM_FEATURE",
	Service = "SERVICE",
	ScheduledTask = "SCHEDULED_TASK",
	Shell = "SHELL",
	PortableBinary = "PORTABLE_BINARY",
	WslDistribution = "WSL_DISTRIBUTION",
	DockerContext = "DOCKER_CONTEXT",
	DockerImage = "DOCKER_IMAGE",
	DockerVolume = "DOCKER_VOLUME",
	Unknown = "UNKNOWN",
}

export enum IdentityQuality {
	Provider = "PROVIDER",
	PackageFamily = "PACKAGE_FAMILY",
	SignedProduct = "SIGNED_PRODUCT",
	Product = "PRODUCT",
	Local = "LOCAL",
}

export interface Identity {
	provider_package?: [ProviderId, string];
	provider_source?: string;
	package_family?: string;
	product_name?: string;
	executable_name?: string;
	publisher?: string;
	executable_hash?: string;
	install_role?: string;
	identity_quality: IdentityQuality;
}

export interface VersionValue {
	raw: string;
	normalized?: string;
}

export enum Architecture {
	X86 = "X86",
	X64 = "X64",
	Arm64 = "ARM64",
	Neutral = "NEUTRAL",
	Unknown = "UNKNOWN",
}

export interface Publisher {
	name: string;
	certificate_thumbprint?: string;
}

/** Opaque provider identifier. Its value is validated for safe wire transport. */
export type ProviderId = string;

export interface Provenance {
	provider?: ProviderId;
	package_id?: string;
	source_url?: string | undefined;
	observed_version?: string;
	adapter_id: string;
	adapter_version: string;
}

/**
 * Opaque evidence identifier. Its value is validated for safe wire transport.
 * Opaque provider identifier. Its value is validated for safe wire transport.
 */
export type EvidenceId = string;

export interface EvidenceRef {
	id: EvidenceId;
	strength: number;
}

export enum Confidence {
	Confirmed = "CONFIRMED",
	High = "HIGH",
	Medium = "MEDIUM",
	Low = "LOW",
	Unknown = "UNKNOWN",
}

export enum DependencyKind {
	RequiredRuntime = "REQUIRED_RUNTIME",
	RequiredPackage = "REQUIRED_PACKAGE",
	InstalledThrough = "INSTALLED_THROUGH",
	Configures = "CONFIGURES",
	UsesSecret = "USES_SECRET",
	OptionalFeature = "OPTIONAL_FEATURE",
	ProvidesExecutable = "PROVIDES_EXECUTABLE",
	Contains = "CONTAINS",
	RestoresBefore = "RESTORES_BEFORE",
	VerifiesWith = "VERIFIES_WITH",
	RelatedOnly = "RELATED_ONLY",
}

export interface DependencyEdge {
	from: ComponentId;
	to: ComponentId;
	kind: DependencyKind;
	required: boolean;
	evidence: EvidenceId[];
	confidence: Confidence;
}

export type KnownFolderToken = 
	| { type: "USER_PROFILE", content?: undefined }
	| { type: "ROAMING_APP_DATA", content?: undefined }
	| { type: "LOCAL_APP_DATA", content?: undefined }
	| { type: "PROGRAM_DATA", content?: undefined }
	| { type: "PROGRAM_FILES", content?: undefined }
	| { type: "PROGRAM_FILES_X86", content?: undefined }
	| { type: "START_MENU", content?: undefined }
	| { type: "STARTUP", content?: undefined }
	| { type: "DESKTOP", content?: undefined }
	| { type: "DOCUMENTS", content?: undefined }
	| { type: "USER_SELECTED", content: {
	id: string;
}};

export interface PathToken {
	root: KnownFolderToken;
	relative: string;
}

export enum ConfigScope {
	Process = "PROCESS",
	User = "USER",
	System = "SYSTEM",
	Project = "PROJECT",
	Managed = "MANAGED",
}

export enum ContentType {
	Utf8Text = "UTF8_TEXT",
	Json = "JSON",
	Jsonc = "JSONC",
	Toml = "TOML",
	Binary = "BINARY",
	Archive = "ARCHIVE",
	Unknown = "UNKNOWN",
}

export enum ArtifactPolicy {
	Config = "CONFIG",
	Data = "DATA",
	Export = "EXPORT",
	PortableBinary = "PORTABLE_BINARY",
	LargeOptIn = "LARGE_OPT_IN",
	SecretReference = "SECRET_REFERENCE",
	Manual = "MANUAL",
}

/** Content-addressed object identity: `obj_` followed by lowercase hexadecimal BLAKE3-256. */
export type ObjectId = string;

export interface ArtifactRef {
	id: ArtifactId;
	source_path: PathToken;
	scope: ConfigScope;
	size_bytes: number;
	content_type: ContentType;
	policy: ArtifactPolicy;
	object?: ObjectId;
}

export enum RestoreStrategy {
	Reinstall = "REINSTALL",
	ConfigPortable = "CONFIG_PORTABLE",
	DataPortable = "DATA_PORTABLE",
	ExportImport = "EXPORT_IMPORT",
	PortableBinary = "PORTABLE_BINARY",
	SecretExportable = "SECRET_EXPORTABLE",
	ReauthRequired = "REAUTH_REQUIRED",
	MachineBound = "MACHINE_BOUND",
	Partial = "PARTIAL",
	Manual = "MANUAL",
	Unknown = "UNKNOWN",
}

export enum Portability {
	Portable = "PORTABLE",
	SupportedExport = "SUPPORTED_EXPORT",
	SyncRestorable = "SYNC_RESTORABLE",
	PartiallyPortable = "PARTIALLY_PORTABLE",
	ApplicationBound = "APPLICATION_BOUND",
	UserBound = "USER_BOUND",
	MachineBound = "MACHINE_BOUND",
	ReauthRequired = "REAUTH_REQUIRED",
	Unsupported = "UNSUPPORTED",
	Unknown = "UNKNOWN",
}

export interface RestoreDescriptor {
	primary: RestoreStrategy;
	alternatives: RestoreStrategy[];
	portability: Portability;
	requires_elevation: boolean;
	requires_user_action: boolean;
	rationale: string[];
}

export interface Compatibility {
	required_os?: string;
	required_architecture?: Architecture;
	requires_provider?: ProviderId;
	requires_runtime?: ComponentId;
	requires_elevation: boolean;
	requires_wsl: boolean;
	requires_docker: boolean;
}

export type VerificationRule = 
	| { type: "PROVIDER_IDENTITY", content: {
	provider: ProviderId;
	package: PackageSpec;
}}
	| { type: "FILE", content: {
	destination: TokenizedPath;
	object?: ObjectId;
}}
	| { type: "FILE_VERSION", content: {
	destination: TokenizedPath;
	version?: VersionValue;
	publisher?: Publisher;
}}
	| { type: "CONFIG_PARSES", content: {
	destination: TokenizedPath;
	content_type: ContentType;
}}
	| { type: "ENVIRONMENT", content: {
	scope: ConfigScope;
	name: string;
	expected: SafeValueRef;
}}
	| { type: "MCP_REGISTRATION", content: {
	name: string;
	config: TokenizedPath;
}}
	| { type: "WSL_STATE", content: {
	distro: string;
	version?: string;
}}
	| { type: "DOCKER_OBJECT", content: {
	kind: ComponentKind;
	identity: string;
}}
	| { type: "BROWSER_ARTIFACT", content: {
	profile: TokenizedPath;
}}
	| { type: "SECURE_TARGET", content: {
	secret: ComponentId;
}};

export interface SelectionMetadata {
	recommended: boolean;
	score: number;
	selected_by_default: boolean;
	sensitive: boolean;
	size_bytes: number;
}

export interface Component {
	id: ComponentId;
	kind: ComponentKind;
	identity: Identity;
	display_name: string;
	version?: VersionValue;
	architecture?: Architecture;
	publisher?: Publisher;
	provenance?: Provenance;
	evidence: EvidenceRef[];
	confidence: Confidence;
	dependencies: DependencyEdge[];
	artifacts: ArtifactRef[];
	restore: RestoreDescriptor;
	compatibility: Compatibility;
	verification: VerificationRule[];
	selection: SelectionMetadata;
}

export interface PackageGraph {
	components: Component[];
	edges: DependencyEdge[];
}

export type ComponentGraph = PackageGraph;

export type SafeValueRef = 
	| { type: "LITERAL_NON_SECRET", content: string }
	| { type: "ENVIRONMENT_REFERENCE", content: {
	name: string;
}}
	| { type: "SECRET_REFERENCE", content: {
	id: ComponentId;
	label: string;
}}
	| { type: "REDACTED_UNKNOWN", content?: undefined };

export type McpArgument = SafeValueRef;

/** Stable operation identity in the form `op_<run-id>_<decimal-ordinal>`. */
export type OperationId = string;

/** UUIDv7 run identifier used to correlate resumable operations and journal events. */
export type RunId = string;

/**
 * Opaque snapshot identifier. Its value is validated for safe wire transport.
 * Opaque artifact identifier. Its value is validated for safe wire transport.
 */
export type SnapshotId = string;

export type TokenizedPath = PathToken;

export interface ArtifactSelection {
	artifact: ArtifactId;
	include: boolean;
}

export enum ReforgeErrorCode {
	AccessDenied = "ACCESS_DENIED",
	PathNotFound = "PATH_NOT_FOUND",
	FileLocked = "FILE_LOCKED",
	InvalidPath = "INVALID_PATH",
	ReparsePoint = "REPARSE_POINT",
	ProviderUnavailable = "PROVIDER_UNAVAILABLE",
	ProviderParseFailed = "PROVIDER_PARSE_FAILED",
	SourceUnavailable = "SOURCE_UNAVAILABLE",
	VersionUnavailable = "VERSION_UNAVAILABLE",
	PackageNotFound = "PACKAGE_NOT_FOUND",
	PackageCorrupt = "PACKAGE_CORRUPT",
	PackageUntrusted = "PACKAGE_UNTRUSTED",
	VaultRequired = "VAULT_REQUIRED",
	VaultDecryptFailed = "VAULT_DECRYPT_FAILED",
	SecretNotPortable = "SECRET_NOT_PORTABLE",
	ManualSecretRequired = "MANUAL_SECRET_REQUIRED",
	SchemaInvalid = "SCHEMA_INVALID",
	UnsupportedVersion = "UNSUPPORTED_VERSION",
	ArchitectureConflict = "ARCHITECTURE_CONFLICT",
	OsConflict = "OS_CONFLICT",
	InsufficientDisk = "INSUFFICIENT_DISK",
	DependencyCycle = "DEPENDENCY_CYCLE",
	SelectionIncomplete = "SELECTION_INCOMPLETE",
	TargetConflict = "TARGET_CONFLICT",
	SecurityPolicy = "SECURITY_POLICY",
	ManualActionRequired = "MANUAL_ACTION_REQUIRED",
	UserActionRequired = "USER_ACTION_REQUIRED",
	RebootRequired = "REBOOT_REQUIRED",
	OperationFailed = "OPERATION_FAILED",
	InstallFailed = "INSTALL_FAILED",
	VerificationFailed = "VERIFICATION_FAILED",
	Interrupted = "INTERRUPTED",
	Cancelled = "CANCELLED",
}

export enum RiskLevel {
	Low = "LOW",
	Medium = "MEDIUM",
	High = "HIGH",
	Critical = "CRITICAL",
}

export enum ManualActionState {
	Pending = "PENDING",
	Acknowledged = "ACKNOWLEDGED",
	Completed = "COMPLETED",
	Skipped = "SKIPPED",
}

export interface ManualAction {
	id: string;
	component?: ComponentId;
	title: string;
	reason: string;
	risk: RiskLevel;
	instructions: string[];
	docs_url?: string | undefined;
	state: ManualActionState;
	independent_operations_may_continue: boolean;
	acknowledged_at?: string | undefined;
	verification?: VerificationRule;
}

export interface Blocker {
	code: ReforgeErrorCode;
	component?: ComponentId;
	reason: string;
	required_action?: ManualAction;
}

export interface ChunkRef {
	id: ObjectId;
	uncompressed_bytes: number;
}

export enum CompatibilityStatus {
	Ready = "READY",
	RequiresConfirmation = "REQUIRES_CONFIRMATION",
	Blocked = "BLOCKED",
}

export interface Confirmation {
	id: string;
	component?: ComponentId;
	reason: string;
	risk: RiskLevel;
}

export interface CompatibilityResult {
	status: CompatibilityStatus;
	blockers: Blocker[];
	confirmations: Confirmation[];
	warnings: string[];
}

export enum ReportStatus {
	Verified = "VERIFIED",
	PartiallyVerified = "PARTIALLY_VERIFIED",
	AlreadyPresent = "ALREADY_PRESENT",
	Skipped = "SKIPPED",
	WaitingForUser = "WAITING_FOR_USER",
	ReauthRequired = "REAUTH_REQUIRED",
	RebootRequired = "REBOOT_REQUIRED",
	Unsupported = "UNSUPPORTED",
	Failed = "FAILED",
}

export interface VerificationEvidence {
	rule: VerificationRule;
	status: ReportStatus;
	summary: string;
	observed_at: string;
}

export interface ComponentReport {
	component: ComponentId;
	status: ReportStatus;
	evidence: VerificationEvidence[];
	manual_actions: string[];
	warnings: string[];
}

export enum ConflictKind {
	AlreadySatisfied = "ALREADY_SATISFIED",
	VersionDifference = "VERSION_DIFFERENCE",
	ConfigDifference = "CONFIG_DIFFERENCE",
	DataCollision = "DATA_COLLISION",
	SecretCollision = "SECRET_COLLISION",
	PathCollision = "PATH_COLLISION",
	PortCollision = "PORT_COLLISION",
	DependencyConflict = "DEPENDENCY_CONFLICT",
	ArchitectureConflict = "ARCHITECTURE_CONFLICT",
	UnsupportedTarget = "UNSUPPORTED_TARGET",
}

export enum ConflictResolution {
	Skip = "SKIP",
	Install = "INSTALL",
	Replace = "REPLACE",
	Merge = "MERGE",
	PreserveTarget = "PRESERVE_TARGET",
	Manual = "MANUAL",
}

export interface Conflict {
	id: string;
	component?: ComponentId;
	kind: ConflictKind;
	source_summary: string;
	target_summary: string;
	resolution: ConflictResolution;
	requires_confirmation: boolean;
}

export interface DockerImageSpec {
	repository: string;
	tag?: string;
	image_id?: string;
}

export interface DockerVolumeSpec {
	name: string;
	driver?: string;
}

export interface DriveFact {
	token: string;
	filesystem?: string;
}

export interface DriveFreeSpace {
	token: string;
	bytes: number;
}

export interface EnvBinding {
	name: string;
	value: SafeValueRef;
}

export interface EnvironmentFact {
	scope: ConfigScope;
	name: string;
	value_hash?: string;
}

export enum Retryability {
	Never = "NEVER",
	SafeRetry = "SAFE_RETRY",
	RequiresUserAction = "REQUIRES_USER_ACTION",
	AfterReboot = "AFTER_REBOOT",
}

export interface ErrorEnvelope {
	code: ReforgeErrorCode;
	message: string;
	technical_detail?: string;
	component?: ComponentId;
	operation?: OperationId;
	retryability: Retryability;
	context_id?: string;
}

export enum EvidenceSource {
	Registry = "REGISTRY",
	AppPaths = "APP_PATHS",
	Shortcut = "SHORTCUT",
	FileMetadata = "FILE_METADATA",
	Authenticode = "AUTHENTICODE",
	WinGet = "WIN_GET",
	Chocolatey = "CHOCOLATEY",
	Scoop = "SCOOP",
	Npm = "NPM",
	Pnpm = "PNPM",
	Yarn = "YARN",
	Bun = "BUN",
	Python = "PYTHON",
	Rust = "RUST",
	Go = "GO",
	Dotnet = "DOTNET",
	PowerShell = "POWER_SHELL",
	Wsl = "WSL",
	Docker = "DOCKER",
	Browser = "BROWSER",
	Editor = "EDITOR",
	Harness = "HARNESS",
	UserSelected = "USER_SELECTED",
	Unknown = "UNKNOWN",
}

export interface Evidence {
	id: EvidenceId;
	source: EvidenceSource;
	locator: string;
	observed_at: string;
	summary: string;
	strength: number;
	independent_group: string;
}

export interface ExecutableRef {
	name: string;
	component?: ComponentId;
	observed_path?: PathToken;
}

/** One explainable score contribution or safety override. */
export interface ExplanationChip {
	code: string;
	label: string;
	delta: number;
}

export interface ExplanationChip {
	code: string;
	label: string;
	delta: number;
}

export interface FileManifest {
	size_bytes: number;
	chunks: ChunkRef[];
	content_type: ContentType;
	attributes: number;
}

export enum AccountScope {
	User = "USER",
	Machine = "MACHINE",
}

export interface HostFacts {
	os_version: string;
	os_build: string;
	architecture: Architecture;
	elevated: boolean;
	account_scope: AccountScope;
	sid_fingerprint?: string;
	known_folders: PathToken[];
	drives: DriveFact[];
	free_bytes: DriveFreeSpace[];
}

export interface InstalledFact {
	kind: ComponentKind;
	identity: Identity;
	version?: VersionValue;
	publisher?: Publisher;
	provenance?: Provenance;
}

export interface Inventory {
	format_version: number;
	scan_id: RunId;
	captured_at: string;
	host: HostFacts;
	graph: ComponentGraph;
	evidence: Evidence[];
	warnings: string[];
}

export enum McpTransport {
	Stdio = "STDIO",
	StreamableHttp = "STREAMABLE_HTTP",
	Sse = "SSE",
	Unknown = "UNKNOWN",
}

export type McpWorkingDirectory = 
	| { type: "TOKENIZED", content: PathToken }
	| { type: "ENVIRONMENT_REFERENCE", content: {
	name: string;
}}
	| { type: "SECRET_REFERENCE", content: {
	id: ComponentId;
	label: string;
}}
	| { type: "REDACTED_UNKNOWN", content?: undefined };

export type McpEndpoint = 
	| { type: "PUBLIC", content: string }
	| { type: "ENVIRONMENT_REFERENCE", content: {
	name: string;
}}
	| { type: "SECRET_REFERENCE", content: {
	id: ComponentId;
	label: string;
}}
	| { type: "REDACTED_UNKNOWN", content?: undefined };

export interface PackageSpec {
	provider: ProviderId;
	id: string;
	version?: string;
	source_name?: string;
	source_identifier?: string;
	source?: string | undefined;
	architecture?: Architecture;
	installer_hash?: string;
}

export interface McpServerSpec {
	name: string;
	scope: ConfigScope;
	transport: McpTransport;
	command?: ExecutableRef;
	args: McpArgument[];
	cwd?: McpWorkingDirectory;
	endpoint?: McpEndpoint;
	environment: EnvBinding[];
	required_runtime?: ComponentId;
	required_package?: PackageSpec;
	source_config: ArtifactRef;
}

export interface ObjectEntry {
	id: ObjectId;
	uncompressed_bytes: number;
	compressed_bytes: number;
	content_type: ContentType;
}

export interface ObjectIndex {
	objects: ObjectEntry[];
}

export type OperationKind = 
	| { type: "ENSURE_PROVIDER", content: {
	provider: ProviderId;
}}
	| { type: "INSTALL_PACKAGE", content: {
	provider: ProviderId;
	package: PackageSpec;
	policy: PackageInstallPolicy;
}}
	| { type: "ENSURE_RUNTIME", content: {
	runtime: RuntimeSpec;
}}
	| { type: "WRITE_FILE", content: {
	destination: TokenizedPath;
	object: ObjectId;
	mode: FileMode;
}}
	| { type: "MERGE_JSON", content: {
	destination: TokenizedPath;
	object: ObjectId;
	policy: MergePolicy;
}}
	| { type: "MERGE_TOML", content: {
	destination: TokenizedPath;
	object: ObjectId;
	policy: MergePolicy;
}}
	| { type: "SET_USER_ENVIRONMENT", content: {
	name: string;
	value: SafeValueRef;
}}
	| { type: "APPEND_USER_PATH", content: {
	entries: TokenizedPath[];
}}
	| { type: "IMPORT_WSL", content: {
	distro: WslSpec;
	object: ObjectId;
}}
	| { type: "RESTORE_DOCKER_IMAGE", content: {
	image: DockerImageSpec;
	object: ObjectId;
}}
	| { type: "RESTORE_DOCKER_VOLUME", content: {
	volume: DockerVolumeSpec;
	object: ObjectId;
}}
	| { type: "INSTALL_VS_CODE_EXTENSION", content: {
	id: string;
	version?: string;
	profile?: string;
}}
	| { type: "REGISTER_MCP", content: {
	server: McpServerSpec;
}}
	| { type: "OPEN_MANUAL_ACTION", content: {
	action: ManualAction;
}}
	| { type: "REQUIRE_REBOOT", content: {
	reason: string;
}}
	| { type: "VERIFY", content: {
	rule: VerificationRule;
}};

export type Precondition = 
	| { type: "ALWAYS", content?: undefined }
	| { type: "TARGET_FINGERPRINT", content: {
	fingerprint: string;
}}
	| { type: "COMPONENT_ABSENT", content: {
	component: ComponentId;
}}
	| { type: "COMPONENT_VERSION", content: {
	component: ComponentId;
	minimum?: VersionValue;
}}
	| { type: "ARTIFACT_PRESENT", content: {
	object: ObjectId;
}}
	| { type: "MANUAL_APPROVAL", content: {
	action: string;
}};

export interface Operation {
	id: OperationId;
	component: ComponentId;
	kind: OperationKind;
	prerequisites: OperationId[];
	precondition: Precondition;
	idempotency_key: string;
	verification: VerificationRule[];
	requires_elevation: boolean;
	non_idempotent: boolean;
}

export interface PackageInstallPolicy {
	accept_source_agreements: boolean;
	accept_package_agreements: boolean;
	silent: boolean;
	allow_reboot: boolean;
}

export interface SourceHostSummary {
	os_version: string;
	os_build: string;
	architecture: Architecture;
	known_folder_tokens: KnownFolderToken[];
}

export interface PackageManifest {
	package_id: string;
	format_version: number;
	created_at: string;
	source_host: SourceHostSummary;
	required_os?: string;
	required_architecture?: Architecture;
	component_ids: ComponentId[];
	warnings: string[];
	object_index_digest: string;
}

export enum ScanPhase {
	HostPreflight = "HOST_PREFLIGHT",
	PackageExports = "PACKAGE_EXPORTS",
	WindowsRegistration = "WINDOWS_REGISTRATION",
	RuntimeProbes = "RUNTIME_PROBES",
	KnownFolderConfig = "KNOWN_FOLDER_CONFIG",
	AppAdapters = "APP_ADAPTERS",
	GenericExecutables = "GENERIC_EXECUTABLES",
	Correlation = "CORRELATION",
}

export enum ProgressStatus {
	Started = "STARTED",
	Progress = "PROGRESS",
	Completed = "COMPLETED",
	Warning = "WARNING",
	WaitingForUser = "WAITING_FOR_USER",
	Failed = "FAILED",
	Cancelled = "CANCELLED",
}

export interface ProgressEvent {
	run_id: RunId;
	phase: ScanPhase;
	status: ProgressStatus;
	current_component?: ComponentId;
	completed: number;
	total?: number;
	bytes?: number;
	message: string;
}

export interface ProviderFact {
	id: ProviderId;
	version?: VersionValue;
	available: boolean;
}

/** The deterministic recommendation result for one component. */
export interface RecommendationScore {
	component: ComponentId;
	score: number;
	recommended: boolean;
	chips: ExplanationChip[];
}

export interface RecommendationScore {
	component: ComponentId;
	score: number;
	recommended: boolean;
	chips: ExplanationChip[];
}

export interface ReportCounts {
	verified: number;
	partial: number;
	already_present: number;
	waiting_for_user: number;
	reauth_required: number;
	reboot_required: number;
	unsupported: number;
	failed: number;
}

export enum RestoreMode {
	Rebuild = "REBUILD",
	Migration = "MIGRATION",
}

export interface RestorePlan {
	format_version: number;
	run_id: RunId;
	package_id: string;
	mode: RestoreMode;
	target_fingerprint: string;
	selected_components: ComponentId[];
	operations: Operation[];
	conflicts: Conflict[];
	manual_actions: ManualAction[];
	warnings: string[];
}

export interface RestoreReport {
	format_version: number;
	run_id: RunId;
	package_id: string;
	status: ReportStatus;
	counts: ReportCounts;
	components: ComponentReport[];
	manual_actions: ManualAction[];
	warnings: string[];
	elapsed_ms: number;
	bytes_written: number;
}

export interface RuntimeFact {
	id: ComponentId;
	version?: VersionValue;
	architecture?: Architecture;
}

export interface RuntimeSpec {
	id: string;
	version?: string;
	architecture?: Architecture;
}

export interface SelectionClosure {
	selected_components: ComponentId[];
	selected_artifacts: ArtifactId[];
	auto_added_dependencies: ComponentId[];
	total_bytes: number;
	warnings: string[];
}

export enum SecretSelectionPolicy {
	Exclude = "EXCLUDE",
	VaultExplicit = "VAULT_EXPLICIT",
}

export enum LargeDataSelectionPolicy {
	Exclude = "EXCLUDE",
	RequireConfirmation = "REQUIRE_CONFIRMATION",
}

export enum UnknownBinarySelectionPolicy {
	Exclude = "EXCLUDE",
	PortableBinaryExplicit = "PORTABLE_BINARY_EXPLICIT",
}

export interface SelectionPolicy {
	secrets: SecretSelectionPolicy;
	large_data: LargeDataSelectionPolicy;
	unknown_binaries: UnknownBinarySelectionPolicy;
	max_bytes?: number;
}

export interface SelectionInput {
	components: ComponentId[];
	artifacts: ArtifactSelection[];
	policy: SelectionPolicy;
}

export interface SnapshotManifest {
	snapshot_id: SnapshotId;
	base_snapshot_id?: SnapshotId;
	package: PackageManifest;
	reused_objects: ObjectId[];
	new_objects: ObjectId[];
}

export interface TargetFacts {
	host: HostFacts;
	installed: InstalledFact[];
	providers: ProviderFact[];
	runtimes: RuntimeFact[];
	environment: EnvironmentFact[];
	fingerprint: string;
}

export interface TransportReceipt {
	package_id: string;
	object_count: number;
	index_digest: string;
}

export interface WireEnvelope<T> {
	schema_version: number;
	request_id: string;
	payload: T;
}

export interface WslSpec {
	distribution: string;
	wsl_version?: number;
}

export enum ApprovalState {
	Pending = "PENDING",
	Approved = "APPROVED",
	Rejected = "REJECTED",
}

export enum FileMode {
	PreserveTarget = "PRESERVE_TARGET",
	Replace = "REPLACE",
	CreateOnly = "CREATE_ONLY",
}

export enum MergePolicy {
	PreserveUnknown = "PRESERVE_UNKNOWN",
	ReplaceKnownKeys = "REPLACE_KNOWN_KEYS",
	AppendUnique = "APPEND_UNIQUE",
	ManualOnConflict = "MANUAL_ON_CONFLICT",
}

export enum OperationState {
	Pending = "PENDING",
	Running = "RUNNING",
	Completed = "COMPLETED",
	Failed = "FAILED",
	Skipped = "SKIPPED",
	WaitingForUser = "WAITING_FOR_USER",
	WaitingForReboot = "WAITING_FOR_REBOOT",
	Interrupted = "INTERRUPTED",
	Cancelled = "CANCELLED",
}

export enum RunStatus {
	Planned = "PLANNED",
	WaitingForApproval = "WAITING_FOR_APPROVAL",
	Running = "RUNNING",
	WaitingForUser = "WAITING_FOR_USER",
	WaitingForReboot = "WAITING_FOR_REBOOT",
	Completed = "COMPLETED",
	Partial = "PARTIAL",
	Failed = "FAILED",
	Cancelled = "CANCELLED",
	Interrupted = "INTERRUPTED",
}

export enum TrustState {
	Unchecked = "UNCHECKED",
	IntegrityVerified = "INTEGRITY_VERIFIED",
	Unsigned = "UNSIGNED",
	SignatureInvalid = "SIGNATURE_INVALID",
	SignatureValidUntrusted = "SIGNATURE_VALID_UNTRUSTED",
	SignatureValidTrusted = "SIGNATURE_VALID_TRUSTED",
	UserApproved = "USER_APPROVED",
	Rejected = "REJECTED",
}

